image: debian/unstable
packages:
  - rlwrap
  - default-jre
  - curl
  - rsync
  - unzip
sources:
  - https://git.sr.ht/~codegouvfr/codegouvfr-public
tasks:
  - prepare: |
      curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
      chmod +x linux-install.sh
      sudo ./linux-install.sh
      curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
      chmod +x install-clj-kondo
      sudo ./install-clj-kondo
  - lint: |
      cd codegouvfr-public
      clj-kondo --lint src
  - build: |
      cd codegouvfr-public
      git checkout preproduction
      clojure -M:js
  - upload: |
      cd codegouvfr-public/resources/public/
      rsync -e "ssh -o StrictHostKeyChecking=no" -av * web@libre-01.infra.data.gouv.fr:/home/web/websites/code.gouv.fr_public/preproduction/
triggers:
  - action: email
    condition: failure
    to: bastien.guerry@code.gouv.fr
