image: debian/unstable
packages:
  - rlwrap
  - default-jre
  - curl
  - rsync
  - unzip
secrets:
  - bdd50953-add5-4ddb-9f34-9f0781900b7e
sources:
  - https://git.sr.ht/~codegouvfr/codegouvfr-sources
tasks:
  - prepare: |
      curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
      chmod +x linux-install.sh
      sudo ./linux-install.sh
      curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
      chmod +x install-clj-kondo
      sudo ./install-clj-kondo
  - lint: |
      cd codegouvfr-sources
      clj-kondo --lint src
  - build: |
      cd codegouvfr-sources
      git checkout preproduction
      clojure -M:js
  - upload: |
      cd codegouvfr-sources/resources/public/
      rsync -e "ssh -o StrictHostKeyChecking=no" -av * web@code.gouv.fr:/home/web/websites/code.gouv.fr_sources/preproduction/
triggers:
  - action: email
    condition: failure
    to: bastien.guerry@code.gouv.fr
