image: archlinux
packages:
  - rlwrap
  - jre
  - curl
  - rsync
secrets:
  - d8f306d1-0290-4049-8bb4-a3f47d871b75
tasks:
  - prepare: |
      curl -O https://download.clojure.org/install/linux-install-1.11.1.1113.sh
      chmod +x linux-install-1.11.1.1113.sh
      sudo ./linux-install-1.11.1.1113.sh
  - build: |
      cd code.gouv.fr
      git checkout production
      clojure -M:js
  - upload: |
      cd code.gouv.fr/resources/public/
      rsync -e "ssh -o StrictHostKeyChecking=no" -av * web@libre-01.infra.data.gouv.fr:/home/web/websites/code.gouv.fr/
triggers:
  - action: email
    condition: failure
    to: bastien.guerry@data.gouv.fr
