image: debian/unstable
packages:
  - rlwrap
  - default-jre
  - curl
  - rsync
secrets:
  - eefc72cb-a612-4b95-a3e4-dae77d4f1fcf
tasks:
  - prepare: |
      curl -O https://download.clojure.org/install/linux-install-1.11.1.1149.sh
      chmod +x linux-install-1.11.1.1149.sh
      sudo ./linux-install-1.11.1.1149.sh
  - build: |
      cd code.gouv.fr
      git checkout production
      clojure -M:js
  - upload: |
      cd code.gouv.fr/resources/public/
      rsync -e "ssh -o StrictHostKeyChecking=no" -av * web@libre-01.infra.data.gouv.fr:/home/web/websites/code.gouv.fr/
triggers:
  - action: email
    condition: failure
    to: bastien.guerry@code.gouv.fr
