name: Run tests

on: [push, pull_request]

jobs:

  run-tests:
    runs-on: ubuntu-latest
    env:
      SMTP_HOST: localhost
      SMTP_LOGIN: toto
      SMTP_PASSWORD: secr3t
      CODEGOUVFR_ADMIN_EMAIL: toto@example.org
      CODEGOUVFR_FROM: toto@example.org
      CODEGOUVFR_PORT: 1337
      CODEGOUVFR_GITHUB_USER: example
      CODEGOUVFR_GITHUB_ACCESS_TOKEN: some-token

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Install clojure tools-deps
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: 1.10.1.693

      - name: Run tests
        run: clojure -Mtest
